//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#ifndef _NANOFRAMEWORK_HARDWARE_ESP32_BLUETOOTH_H_
#define _NANOFRAMEWORK_HARDWARE_ESP32_BLUETOOTH_H_

#include <nanoCLR_Interop.h>
#include <nanoCLR_Runtime.h>

struct Library_nanoFramework_Hardware_Esp32_Bluetooth_nanoFramework_Hardware_Esp32_Bluetooth_BTLEService
{
    NANOCLR_NATIVE_DECLARE(NativeCheckInterop___STATIC__VOID__STRING);

    //--//

};

extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_nanoFramework_Hardware_Esp32_Bluetooth;

#endif  //_NANOFRAMEWORK_HARDWARE_ESP32_BLUETOOTH_H_
